project:
  type: website

website:
  title: IMAS Marine Predator Lab | Marine Mammal and Seabird Research
  open-graph: true
  navbar:
    title: false
    logo: mpredlab-logo-white.svg
    logo-alt: IMAS MPred Lab (Marine Predator Lab)
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - publications.qmd
      - href: /#our-research-themes
        text: Research
      - href: contact.qmd
        text: Contact
    right:
      - icon: twitter
        href: https://twitter.com/mpred_lab
  back-to-top-navigation: false
  repo-url: https://github.com/imas-mpred-lab/mpred-lab-website
  repo-actions: [edit, issue]
  twitter-card:
    creator: '@dahliasan'
    site: '@mpredlab'
  google-analytics: 'G-724XDL36LX'
  page-footer:
    left: "built and designed by <a href='https://read.cv/dahliafoo'>dahlia foo</a>"
    right:
      - icon: twitter
        href: https://twitter.com/mpred_lab
format:
  html:
    theme:
      - cyborg
      - 'css/custom.scss'
    toc: true
editor: visual
