project:
  type: website

website:
  title: IMAS Marine Predator Lab | Marine Mammal and Seabird Research
  open-graph: true
  navbar:
    title: false
    logo: mpredlab-logo-white.svg
    logo-alt: IMAS MPred Lab (Marine Predator Lab)
    background: primary
    left:
      - href: index.qmd
        text: Home
      - team.qmd
      - blog.qmd
      - href: contact.qmd
        text: Contact
      - href: /#our-research-themes
        text: Research
    right: 
      - icon: twitter
        href: https://twitter.com/mpred_lab
  back-to-top-navigation: true
  twitter-card:
    creator: "@dahliasan"
    site: "@mpredlab"
  page-footer: 
    left: "built and designed by <a href='https://read.cv/dahliafoo'>dahlia foo</a>" 
    right: 
      - icon: twitter 
        href: https://twitter.com/mpred_lab 

format:
  html:
    theme: 
      dark: [journal, "css/theme-dark.scss", "css/custom.scss"]
      light: [journal, "css/custom.scss"]
    css: "css/styles.css"
    toc: true

editor: visual

